version: '3'

services:
  www:
    image: php:apache
    volumes:
      - .:/var/www/html
    ports:
      - "88:80"

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_database
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      # Consider removing MYSQL_ALLOW_EMPTY_PASSWORD for security reasons
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8988:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
